var cities = {
    "type": "FeatureCollection",
    "name": "KC_tour_cities",
    "features": [
    { "type": "Feature", "properties": { "city": "Clearwater", "state": "FL", "date": "2021-07-22", "month": "July", "order": 1, "venue": "Ruth Eckard Hall" }, "geometry": { "type": "Point", "coordinates": [ -82.7957, 27.9661 ] } },
    { "type": "Feature", "properties": { "city": "Delray Beach", "state": "FL", "date": "2021-07-23", "month": "July", "order": 2, "venue": "Old School Square" }, "geometry": { "type": "Point", "coordinates": [ -80.0738, 26.4658 ] } },
    { "type": "Feature", "properties": { "city": "St. Augustine", "state": "FL", "date": "2021-07-24", "month": "July", "order": 3, "venue": "St. Augustine Amphitheater" }, "geometry": { "type": "Point", "coordinates": [ -81.3118, 29.8933 ] } },
    { "type": "Feature", "properties": { "city": "Orlando", "state": "FL", "date": "2021-07-26", "month": "July", "order": 4, "venue": "Dr. Phillips Walt Disney Theater" }, "geometry": { "type": "Point", "coordinates": [ -81.3762, 28.5358 ] } },
    { "type": "Feature", "properties": { "city": "Atlanta", "state": "GA", "date": "2021-07-27", "month": "July", "order": 5, "venue": "The Fox" }, "geometry": { "type": "Point", "coordinates": [ -84.3897, 33.7488 ] } },
    { "type": "Feature", "properties": { "city": "Nashville", "state": "TN", "date": "2021-07-28", "month": "July", "order": 6, "venue": "Ryman Auditorium" }, "geometry": { "type": "Point", "coordinates": [ -86.7759, 36.1703 ] } },
    { "type": "Feature", "properties": { "city": "Fort Worth", "state": "TX", "date": "2021-07-30", "month": "July", "order": 7, "venue": "Will Rogers Memorial Auditorium" }, "geometry": { "type": "Point", "coordinates": [ -97.3299, 32.7447 ] } },
    { "type": "Feature", "properties": { "city": "Cedar Park", "state": "TX", "date": "2021-07-31", "month": "July", "order": 8, "venue": "H-E-B Center" }, "geometry": { "type": "Point", "coordinates": [ -97.8209, 30.5053 ] } },
    { "type": "Feature", "properties": { "city": "Greenwood Village", "state": "CO", "date": "2021-08-02", "month": "August", "order": 9, "venue": "Fiddlers Green Amphitheater" }, "geometry": { "type": "Point", "coordinates": [ -104.9928, 39.7397 ] } },
    { "type": "Feature", "properties": { "city": "Sandy", "state": "UT", "date": "2021-08-03", "month": "August", "order": 10, "venue": "Sandy Amphitheater" }, "geometry": { "type": "Point", "coordinates": [ -111.894, 40.5703 ] } },
    { "type": "Feature", "properties": { "city": "Concord", "state": "CA", "date": "2021-08-05", "month": "August", "order": 11, "venue": "Concord Pavilion" }, "geometry": { "type": "Point", "coordinates": [ -122.0243, 37.9832 ] } },
    { "type": "Feature", "properties": { "city": "Los Angeles", "state": "CA", "date": "2021-08-06", "month": "August", "order": 12, "venue": "The Greek" }, "geometry": { "type": "Point", "coordinates": [ -118.2399, 34.0532 ] } },
    { "type": "Feature", "properties": { "city": "Scottsdale", "state": "AZ", "date": "2021-08-07", "month": "August", "order": 13, "venue": "Talking Stick Ballroom" }, "geometry": { "type": "Point", "coordinates": [ -111.9225, 33.4957 ] } },
    { "type": "Feature", "properties": { "city": "Saratoga Springs", "state": "NY", "date": "2021-08-23", "month": "August", "order": 14, "venue": "SPAC" }, "geometry": { "type": "Point", "coordinates": [ -73.7844, 43.0732 ] } },
    { "type": "Feature", "properties": { "city": "Northhampton", "state": "MA", "date": "2021-08-24", "month": "August", "order": 15, "venue": "The Pines Theater" }, "geometry": { "type": "Point", "coordinates": [ -72.6317, 42.3174 ] } },
    { "type": "Feature", "properties": { "city": "Canandaigua", "state": "NY", "date": "2021-08-26", "month": "August", "order": 16, "venue": "CMAC" }, "geometry": { "type": "Point", "coordinates": [ -77.28, 42.8884 ] } },
    { "type": "Feature", "properties": { "city": "Lewiston", "state": "NY", "date": "2021-08-27", "month": "August", "order": 17, "venue": "Artpark Amphitheater" }, "geometry": { "type": "Point", "coordinates": [ -79.0476, 43.1727 ] } },
    { "type": "Feature", "properties": { "city": "Rochester Hills", "state": "MI", "date": "2021-08-28", "month": "August", "order": 18, "venue": "Meadow Brook Amphitheater" }, "geometry": { "type": "Point", "coordinates": [ -83.0465, 42.3327 ] } },
    { "type": "Feature", "properties": { "city": "Highland Park", "state": "IL", "date": "2021-08-29", "month": "August", "order": 19, "venue": "Ravinia" }, "geometry": { "type": "Point", "coordinates": [ -87.6279, 41.882 ] } },
    { "type": "Feature", "properties": { "city": "Milwaukee", "state": "WI", "date": "2021-08-31", "month": "August", "order": 20, "venue": "Miller High Life Theater" }, "geometry": { "type": "Point", "coordinates": [ -87.9034, 43.0438 ] } },
    { "type": "Feature", "properties": { "city": "Cleveland", "state": "OH", "date": "2021-09-01", "month": "September", "order": 21, "venue": "Jacobs Pavilion" }, "geometry": { "type": "Point", "coordinates": [ -81.6878, 41.5064 ] } },
    { "type": "Feature", "properties": { "city": "Huber Heights", "state": "OH", "date": "2021-09-02", "month": "September", "order": 22, "venue": "Rose Music Center" }, "geometry": { "type": "Point", "coordinates": [ -84.5022, 39.1084 ] } },
    { "type": "Feature", "properties": { "city": "Holmdel", "state": "NJ", "date": "2021-09-04", "month": "September", "order": 23, "venue": "PNC Bank Arts Center" }, "geometry": { "type": "Point", "coordinates": [ -74.0738, 40.4131 ] } },
    { "type": "Feature", "properties": { "city": "New Haven", "state": "CT", "date": "2021-09-05", "month": "September", "order": 24, "venue": "Westville Music Bowl" }, "geometry": { "type": "Point", "coordinates": [ -72.9279, 41.3076 ] } },
    { "type": "Feature", "properties": { "city": "Philadelphia", "state": "PA", "date": "2021-09-07", "month": "September", "order": 25, "venue": "The Mann Center" }, "geometry": { "type": "Point", "coordinates": [ -75.1584, 39.9557 ] } },
    { "type": "Feature", "properties": { "city": "Forest Hills", "state": "NY", "date": "2021-09-09", "month": "September", "order": 26, "venue": "Forest Hills Stadium" }, "geometry": { "type": "Point", "coordinates": [ -73.8201, 40.6861 ] } },
    { "type": "Feature", "properties": { "city": "Boston", "state": "MA", "date": "2021-09-10", "month": "September", "order": 27, "venue": "Leader Bank Pavilion" }, "geometry": { "type": "Point", "coordinates": [ -71.0566, 42.3583 ] } },
    { "type": "Feature", "properties": { "city": "Washington", "state": "DC", "date": "2021-09-11", "month": "September", "order": 28, "venue": "The Anthem" }, "geometry": { "type": "Point", "coordinates": [ -77.0267, 38.8918 ] } }
    ]
    }
    